name: Deploy Ticketing App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to VPS
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << EOF
          set -e

          echo "Switching to project directory"
          cd ${{ secrets.APP_DIR }}

          echo "Pulling latest code"
          git pull origin main

          echo "Stopping existing containers"
          docker compose down

          echo "Building and starting containers"
          docker compose up -d --build

          echo "Deployment complete"
        EOF
